In [15]:
import numpy as M

x  = M.array([1,2,3])

create an matrix which is 
$\left[ \begin{array}{cccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\ \end{array} \right]$

In [20]:
A = M.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
A*x
x*A

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [18]:

M.dot(A,x)

array([14, 32, 50])

In [19]:
M.dot(x,A)

array([30, 36, 42])